server:
  port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/online_bookstore?serverTimezone=UTC
        username: root
        password: 123456
        druid:
          initial-size: 5
          minIdle: 2
    mybatis-plus:
      global-config:
        db-config:
          id-type: auto
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher


configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
